server:
  port: 8091
spring:
  datasource:
    name: vdm_database_users
    host: localhost
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/vdm_database_users
  liquibase:
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driver-class-name}
    parameters:
      spring.datasource.username: ${spring.datasource.username}
      spring.datasource.password: ${spring.datasource.password}

